# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-lg"
BBFILE_PATTERN_meta-lg = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-lg = "6"

LAYERDEPENDS_meta-lg = "core"
LAYERSERIES_COMPAT_meta-lg = "scarthgap"
