include conf/distro/fsl-imx-fb.conf

DISTRO = "advent-calendar"

# Remove conflicting backends
DISTRO_FEATURES:append = " directfb"
DISTRO_FEATURES:remove = "x11 wayland pam"

DISTRO_FEATURES:append = " opengl egl gbm drm"


#PACKAGECONFIG:append:pn-weston      = " rdp"
#PACKAGECONFIG:append:pn-weston-init = " rdp"