require conf/distro/poky.conf

DISTRO = "advent-calendar-raspberry"

POKY_INIT_MANAGER = "systemd"

DISTRO_FEATURES:append = " directfb"
DISTRO_FEATURES:remove = "x11 wayland pam"

DISTRO_FEATURES:append = " opengl egl gbm drm"

#DISTRO_FEATURES:remove = "vulkan"

ENABLE_SPI_BUS = "1"
ENABLE_UART = "1"
RPI_EXTRA_CONFIG:append = " dtparam=audio=on"